'use client';
import {useEffect,useState} from 'react';
import LoginPanel from '../../components/login-panel';
type Account={email:string;name:string;role:'admin'|'employee';enabled:number;hasPassword:number};
export default function AccessPage(){
 const [person,setPerson]=useState<{email:string;admin:boolean}|null>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false);
 const [accounts,setAccounts]=useState<Account[]>([]),[error,setError]=useState(''),[message,setMessage]=useState('');
 const [email,setEmail]=useState(''),[name,setName]=useState(''),[password,setPassword]=useState(''),[role,setRole]=useState<'admin'|'employee'>('employee'),[activating,setActivating]=useState(false);
 async function load(){setLoading(true);try{const auth=await fetch('/api/auth').then(r=>r.json()) as {error?:string;user:{email:string;admin:boolean}|null};if(auth.error)throw Error(auth.error);setPerson(auth.user);if(auth.user?.admin){const response=await fetch('/api/accounts');const data=await response.json() as {error?:string;accounts:Account[]};if(!response.ok)throw Error(data.error);setAccounts(data.accounts);}}catch(e){setError((e as Error).message);}finally{setLoading(false);}}
 useEffect(()=>{void load();},[]);
 async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');setMessage('');try{const response=await fetch('/api/accounts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:activating?'activate':'create',email,name,password,role})});const data=await response.json() as {error?:string};if(!response.ok)throw Error(data.error);setEmail('');setName('');setPassword('');setRole('employee');setActivating(false);await load();setMessage('Adgangen er gemt. Kontoen kan logge ind med e-mail og adgangskode.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function remove(account:Account){
  if(!window.confirm('Fjern '+(account.name||account.email)+' ('+account.email+')? Personen mister adgang med det samme. Allerede gemte frokostvalg bevares.'+(account.email===person?.email?' Du fjerner din egen adgang og bliver logget ud.':'')))return;
  setBusy(true);setError('');setMessage('');
  try{const response=await fetch('/api/accounts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'remove',email:account.email})});const data=await response.json() as {error?:string};if(!response.ok)throw Error(data.error);
   if(email===account.email){setActivating(false);setEmail('');setName('');setPassword('');setRole('employee');}
   await load();setMessage('Adgangen er fjernet. Allerede gemte frokostvalg er bevaret.');
  }catch(e){setError((e as Error).message);}finally{setBusy(false);}
 }
 return <main><header><a className="brand" href="/"><img className="brand-logo" src="/suf-logo.webp" alt="Den Sociale Udviklingsfond" width={800} height={200}/><span className="brand-title">Fredagsfrokost</span></a>{person&&<span className="role-badge">{person.admin?'Administrator':'Bruger'}</span>}</header>
 {loading&&!person?<p role="status">Henter adgang…</p>:!person?<LoginPanel onLogin={load}/>:!person.admin?<section className="login"><h1>Kun for administratorer</h1><p>Din konto har brugeradgang.</p><a href="/" className="page-link">Tilbage til forsiden</a></section>:<>
 <section className="intro"><p className="eyebrow">ADMINISTRATION</p><h1>Adgange</h1><p>Opret eller fjern administratorer og brugere. Alle logger ind med e-mail og adgangskode.</p></section>
 <nav className="view-tabs"><a className="tab-link" href="/">Min frokost</a><a className="tab-link" href="/?view=admin">Administrer retter</a><a className="tab-link selected" href="/adgange" aria-current="page">Adgange</a></nav>
 <section className="signup access-create"><h2>{activating?'Opret adgangskode til eksisterende konto':'Opret ny adgang'}</h2><form onSubmit={save}><label htmlFor="access-name">Navn</label><input id="access-name" autoComplete="off" value={name} onChange={e=>setName(e.target.value)} maxLength={80} required disabled={busy}/><label className="phone-label" htmlFor="access-email">E-mail</label><input id="access-email" type="email" autoComplete="off" value={email} onChange={e=>setEmail(e.target.value)} maxLength={254} required disabled={busy||activating}/><label className="phone-label" htmlFor="access-role">Adgangstype</label><select id="access-role" value={role} onChange={e=>setRole(e.target.value as 'admin'|'employee')} disabled={busy}><option value="employee">Bruger</option><option value="admin">Administrator</option></select><p className="helper">Administratorer kan ændre retter og oprette nye adgange. Brugere kan vælge frokost og se deltagerlisten.</p><label className="phone-label" htmlFor="access-password">Adgangskode (mindst 6 tegn)</label><input id="access-password" type="password" autoComplete="new-password" value={password} onChange={e=>setPassword(e.target.value)} minLength={6} maxLength={72} required disabled={busy}/><button className="primary" disabled={busy}>{busy?'Gemmer…':activating?'Gem adgangskode':role==='admin'?'Opret administrator':'Opret bruger'}</button>{activating&&<button type="button" className="text-button" onClick={()=>{setActivating(false);setEmail('');setName('');setPassword('');setRole('employee');}}>Annuller</button>}</form></section>
 {message&&<p className="success" role="status">{message}</p>}
 <div className="access-lists">{(['admin','employee'] as const).map(type=><section className="attendance" key={type}><h2>{type==='admin'?'Administratoradgang':'Brugeradgang'} ({accounts.filter(a=>a.role===type).length})</h2><ul className="account-list">{accounts.filter(a=>a.role===type).map(a=><li key={a.email}><strong>{a.name||a.email}</strong><span>{a.email}</span><small>{a.hasPassword?'Adgangskode oprettet':'Mangler adgangskode'}</small>{!a.hasPassword&&<button className="text-button" disabled={busy} onClick={()=>{setActivating(true);setEmail(a.email);setName(a.name);setRole(a.role);setPassword('');document.getElementById('access-name')?.focus();}}>Opret adgangskode</button>}<button type="button" className="text-button" disabled={busy} onClick={()=>void remove(a)} aria-label={"Fjern "+(a.name||a.email)}>Fjern</button></li>)}</ul>{!accounts.some(a=>a.role===type)&&<p className="helper">Ingen konti i denne liste endnu.</p>}</section>)}</div>
 </>}{error&&<p className="error" role="alert">{error}</p>}<footer>SUF · Fredagsfrokost</footer></main>;
}

