'use client';
import {useEffect,useState} from 'react';
import LoginPanel from '../../components/login-panel';
type Account={email:string;name:string;role:'admin'|'employee';enabled:number;hasPassword:number};
export default function AccessPage(){
 const [person,setPerson]=useState<{email:string;admin:boolean}|null>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false);
 const [accounts,setAccounts]=useState<Account[]>([]),[error,setError]=useState(''),[message,setMessage]=useState('');
 const [email,setEmail]=useState(''),[name,setName]=useState(''),[role,setRole]=useState<'admin'|'employee'>('employee');
 const [activation,setActivation]=useState<{email:string;code:string}|null>(null);
 async function load(){setLoading(true);try{const auth=await fetch('/api/auth').then(r=>r.json()) as {error?:string;user:{email:string;admin:boolean}|null};if(auth.error)throw Error(auth.error);setPerson(auth.user);if(auth.user?.admin){const response=await fetch('/api/accounts');const data=await response.json() as {error?:string;accounts:Account[]};if(!response.ok)throw Error(data.error);setAccounts(data.accounts);}}catch(e){setError((e as Error).message);}finally{setLoading(false);}}
 useEffect(()=>{void load();},[]);
 async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');setMessage('');setActivation(null);try{const response=await fetch('/api/accounts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'create',email,name,role})});const data=await response.json() as {error?:string;activationCode?:string};if(!response.ok)throw Error(data.error);if(!data.activationCode)throw Error('Engangskoden kunne ikke oprettes.');setActivation({email,code:data.activationCode});setEmail('');setName('');setRole('employee');await load();setMessage('Adgangen er oprettet. Giv engangskoden til brugeren.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function issueCode(account:Account){const reset=!!account.hasPassword;if(reset&&!window.confirm('Nulstil adgangskoden for '+(account.name||account.email)+'? Personen bliver logget ud og skal vælge en ny adgangskode.'))return;setBusy(true);setError('');setMessage('');setActivation(null);try{const response=await fetch('/api/accounts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:reset?'reset-access':'activation-code',email:account.email})});const data=await response.json() as {error?:string;activationCode?:string};if(!response.ok)throw Error(data.error);if(!data.activationCode)throw Error('Engangskoden kunne ikke oprettes.');setActivation({email:account.email,code:data.activationCode});await load();setMessage(reset?'Adgangskoden er nulstillet. Giv den nye engangskode til brugeren.':'Der er lavet en ny engangskode.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function remove(account:Account){
  if(!window.confirm('Fjern '+(account.name||account.email)+' ('+account.email+')? Personen mister adgang med det samme. Allerede gemte frokostvalg bevares.'+(account.email===person?.email?' Du fjerner din egen adgang og bliver logget ud.':'')))return;
  setBusy(true);setError('');setMessage('');
  try{const response=await fetch('/api/accounts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'remove',email:account.email})});const data=await response.json() as {error?:string};if(!response.ok)throw Error(data.error);
   if(email===account.email){setEmail('');setName('');setRole('employee');}
   await load();setMessage('Adgangen er fjernet. Allerede gemte frokostvalg er bevaret.');
  }catch(e){setError((e as Error).message);}finally{setBusy(false);}
 }
 return <main><header><a className="brand" href="/"><img className="brand-logo" src="/suf-logo.webp" alt="Den Sociale Udviklingsfond" width={800} height={200}/><span className="brand-title">Fredagsfrokost</span></a>{person&&<span className="role-badge">{person.admin?'Administrator':'Bruger'}</span>}</header>
 {loading&&!person?<p role="status">Henter adgang…</p>:!person?<LoginPanel onLogin={load}/>:!person.admin?<section className="login"><h1>Kun for administratorer</h1><p>Din konto har brugeradgang.</p><a href="/" className="page-link">Tilbage til forsiden</a></section>:<>
 <section className="intro"><p className="eyebrow">ADMINISTRATION</p><h1>Adgange</h1><p>Opret eller fjern administratorer og brugere. Ved første login vælger personen selv sin adgangskode.</p></section>
 <nav className="view-tabs"><a className="tab-link" href="/">Min frokost</a><a className="tab-link" href="/?view=admin">Administrer retter</a><a className="tab-link selected" href="/adgange" aria-current="page">Adgange</a></nav>
 <section className="signup access-create"><h2>Opret ny adgang</h2><form onSubmit={save}><label htmlFor="access-name">Navn</label><input id="access-name" autoComplete="off" value={name} onChange={e=>setName(e.target.value)} maxLength={80} required disabled={busy}/><label className="phone-label" htmlFor="access-email">E-mail</label><input id="access-email" type="email" autoComplete="off" value={email} onChange={e=>setEmail(e.target.value)} maxLength={254} required disabled={busy}/><label className="phone-label" htmlFor="access-role">Adgangstype</label><select id="access-role" value={role} onChange={e=>setRole(e.target.value as 'admin'|'employee')} disabled={busy}><option value="employee">Bruger</option><option value="admin">Administrator</option></select><p className="helper">Administratorer kan ændre retter og oprette nye adgange. Personen vælger selv sin adgangskode ved første login.</p><button className="primary" disabled={busy}>{busy?'Gemmer…':role==='admin'?'Opret administrator':'Opret bruger'}</button></form></section>
 {activation&&<section className="signup activation-card" aria-live="polite"><h2>Engangskode</h2><p>Giv denne kode til <strong>{activation.email}</strong>. Koden kan kun bruges til at vælge den første eller en ny adgangskode og udløber efter 30 dage.</p><p className="activation-code"><code>{activation.code}</code></p><button type="button" className="text-button" onClick={()=>void navigator.clipboard.writeText(activation.code)}>Kopiér engangskode</button></section>}
 {message&&<p className="success" role="status">{message}</p>}
 <div className="access-lists">{(['admin','employee'] as const).map(type=><section className="attendance" key={type}><h2>{type==='admin'?'Administratoradgang':'Brugeradgang'} ({accounts.filter(a=>a.role===type).length})</h2><ul className="account-list">{accounts.filter(a=>a.role===type).map(a=><li key={a.email}><strong>{a.name||a.email}</strong><span>{a.email}</span><small>{a.hasPassword?'Adgangskode oprettet':'Afventer første login'}</small><button type="button" className="text-button" disabled={busy} onClick={()=>void issueCode(a)}>{a.hasPassword?'Nulstil adgangskode':'Lav ny engangskode'}</button><button type="button" className="text-button" disabled={busy} onClick={()=>void remove(a)} aria-label={"Fjern "+(a.name||a.email)}>Fjern</button></li>)}</ul>{!accounts.some(a=>a.role===type)&&<p className="helper">Ingen konti i denne liste endnu.</p>}</section>)}</div>
 </>}{error&&<p className="error" role="alert">{error}</p>}<footer>SUF · Fredagsfrokost</footer></main>;
}

